### ISSUE TITLE
UnrecognizedPropertyException thrown if the returned error contains a 'data' attribute

### ISSUE THREAD

**Issue by ketola** [arteam/simple-json-rpc#39]
@arteam,  Here's an example of an error response I'm getting from a json-rpc server:
```
{
    "error": {
        "code": -32000,
        "data": null,
        "message": "Server error: xxxx"
    },
    "id": "11111",
    "jsonrpc": "2.0"
}
```
Handling this response causes an exception in the simple-json-rpc client because it seems the 'data' attribute is not handled in the code:

```
aused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "data" (class com.github.arteam.simplejsonrpc.core.domain.ErrorMessage), not marked as ignorable (2 known properties: "code", "message"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.github.arteam.simplejsonrpc.core.domain.ErrorMessage["data"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1192)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4173)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2467)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2920)
	at com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.invoke(ObjectApiBuilder.java:84)
	... 3 more
```
The data attribute should be handled based on the specification: https://www.jsonrpc.org/specification see: 5.1 Error object

**Comment by ketola** [comment]
I found another case that should also be handled. Based on the spec the data attribute can also contain structured data and I found that the server I call can also return that. Here's an example:

```
{
	"error": {
		"code": -32001,
		"data": {
			"major_status": 11,
			"message": null,
			"sub_status": null
		},
		"message": "Server error: VM Validation error: VMStatus { major_status: UNKNOWN_SCRIPT, sub_status: None, message: None }"
	},
	"id": "49abf3f68a942aff5fa1c011cfc10212c462c590",
	"jsonrpc": "2.0"
}
```
