### ISSUE TITLE
param of interface

### ISSUE THREAD

**Issue by lifeinwild** [arteam/simple-json-rpc#42]
I'm not familiar with JSON-RPC.
In my current understanding, it is not possible to call a method whose arguments have interfaces defined. This may be a general JSON-RPC problem.
Is this understanding correct? And is there any solution?

```
	@JsonRpcMethod
	public String getTestMethod(@JsonRpcParam("t") TestI t) {
		System.out.println("serverside " + t.getClass().getName());
		return "returnVal";
	}

	public static interface TestI {

	}

	public static class TestConcrete implements TestI {
		private int i = 3;

		public int getI() {
			return i;
		}

		public void setI(int i) {
			this.i = i;
		}
	}
```

```
		try {
			TestConcrete t = new TestConcrete();
			String res = client.createRequest().method("getTestMethod")
					.id(1L).param("t", t)
					.returnAs(String.class).execute();
			System.out.println("in testcase "+res);
		} catch (Exception e) {
		}

```

**Comment by lifeinwild** [comment]
I noticed this annotation. 
@JsonTypeInfo (use = JsonTypeInfo.Id.CLASS)
However, an exception still occurs.
I thought that polymorphism was not processed.

```
@JsonTypeInfo(use=JsonTypeInfo.Id.CLASS)
public static class TestConcrete implements TestI {
```

```
com.github.arteam.simplejsonrpc.client.exception.JsonRpcException: ErrorMessage{code=-32602, message=Invalid params}
	at com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(RequestBuilder.java:345)
	at com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(RequestBuilder.java:297)
```

**Comment by alexcom** [comment]
This comment is a little bit late of course but still... This issue has to do with Jackson, not with simple-json-rpc. Proper ObjectMapper configuration / `JsonTypeInfo` + `JsonSubTypes` is the key here. So I suggest to close this issue.
