### ISSUE TITLE
CDI bean can not be Json Rpc Service

### ISSUE THREAD

**Issue by mkuligPSI** [arteam/simple-json-rpc#73]
My JsonRpcService is a CDI bean. I inject it to Web socket Server Endpoint. 
```
@Inject
MyJsonRpcService myJsonRpcService;
```
Calling JsonRpcServer#handle(request, myJsonRpcService) throws exception:

```
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: jobExecuted=MethodMetadata{name=jobExecuted, method=public void com.MyJsonRpcService.jobExecuted(com.JobDto), params={job=ParameterMetadata{name=job, type=class com.JobDto, genericType=class com.JobDto, index=0, optional=false}}} and jobExecuted=MethodMetadata{name=jobExecuted, method=public void com.MyJsonRpcService$Proxy$_$$_WeldClientProxy.jobExecuted(com.JobDto), params={job=ParameterMetadata{name=job, type=class com.JobDto, genericType=class com.JobDto, index=0, optional=false}}}
        at deployment.pos.coordinator.service-3.4.0-SNAPSHOT.war//com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
        at deployment.pos.coordinator.service-3.4.0-SNAPSHOT.war//com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
        at deployment.pos.coordinator.service-3.4.0-SNAPSHOT.war//com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
        at deployment.pos.coordinator.service-3.4.0-SNAPSHOT.war//com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
        at deployment.pos.coordinator.service-3.4.0-SNAPSHOT.war//com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
        at deployment.pos.coordinator.service-3.4.0-SNAPSHOT.war//com.github.arteam.simplejsonrpc.server.Reflections.getClassMetadata(Reflections.java:106)
```
There are two methods with the same key:
`com.MyJsonRpcService.jobExecuted`
and
`com.MyJsonRpcService$Proxy$_$$_WeldClientProxy.jobExecuted`

**Comment by mkuligPSI** [comment]
@Singleton annotated beans don’t have a proxy object so JsonRpcService can be Singleton.
